### ISSUE TITLE
Server timing header reports way too many digits increasing payload size

### ISSUE THREAD

**Issue by nojvek** [yosuke-furukawa/server-timing#43]
I'm seeing headers like this.

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 47
Content-Type: application/json; charset=utf-8
Date: Tue, 17 Mar 2020 00:37:45 GMT
ETag: W/"2f-HBVBFjfVjA6RzEQvzkQEL/siiiQ"
Server-Timing: total; dur=21.207006999999997; desc="Total Response Time"
X-Powered-By: Express
```

Due to floating point math, it's very common to get super long numbers like this `21.207006999999997`

To be honest I don't really care about sub microsecond latency. Could we simply return the numbers as `elapsedMs.toFixed(3)`.

It's not like nodejs (v8) will really return nanosecond precision time due to security concerns like Spectre and Meltdown, so those extra numbers are meaningless anyway.

**Comment by yosuke-furukawa** [comment]
it depends on the situation. if you would like to set some option like `precision: millisecond`, that seems good for me. but if server-timing api would like to use benchmark, we need `nanosecond` precision. our default precision would be better `nanosecond` for me.

FYI: if i use performance.now method, the method does not return precisely due to Spectre. But I am using `process.hrtime()`. it is not v8 feature, it uses uv_clock in `libuv` more precise than v8.
